version: '3'
services:
  eureka-server:
    build: ../eureka-server
    image: com.zhoudq/eureka-server
    ports:
      - "8761:8761"
    volumes:
      - .:/tmp
  gateway:
    build: ../gateway
    image: com.zhoudq/gateway
    ports:
      - "8000:8000"
    volumes:
      - .:/tmp
  service-a:
    build: ../service-a
    image: com.zhoudq/service-a
    ports:
      - "8001:8001"
    links:
      - eureka-server
    volumes:
      - .:/tmp