version: '3'
services:
  eureka-server:
    image: com.zhoudq/eureka-server
    ports:
      - "8761:8761"
    volumes:
      - .:/tmp

  service-a:
    image: com.zhoudq/service-a
    ports:
      - "8001:8001"
    links:
      - eureka-server
    volumes:
      - .:/tmp