spring:
  application:
    name: gateway
  profiles:
    active: docker
zuul:
  routes:
    service-a:
      path: /service-a/**
      service-id: service-a
server:
  port: 8000
---
spring:
  profiles: docker
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
---
spring:
  profiles: ide
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
